"""Initial schema all tables

Revision ID: 35dd88de73d8
Revises: 
Create Date: 2026-03-18 09:43:29.502183+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models

# revision identifiers, used by Alembic.
revision: str = '35dd88de73d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('user_type', sa.Enum('owner', 'security_team', name='access_user_type'), nullable=False),
    sa.Column('user_ref', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('ip_country', sa.String(length=2), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ua_browser', sa.String(length=100), nullable=True),
    sa.Column('ua_os', sa.String(length=100), nullable=True),
    sa.Column('ua_is_bot', sa.Boolean(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_created_at'), 'access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_logs_event_type'), 'access_logs', ['event_type'], unique=False)
    op.create_table('csp_violations',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('blocked_uri', sa.Text(), nullable=True),
    sa.Column('violated_directive', sa.String(length=200), nullable=True),
    sa.Column('effective_directive', sa.String(length=200), nullable=True),
    sa.Column('original_policy', sa.Text(), nullable=True),
    sa.Column('document_uri', sa.Text(), nullable=True),
    sa.Column('disposition', sa.String(length=20), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('column_number', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_names',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_normalized', sa.String(length=300), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_names_name_normalized'), 'program_names', ['name_normalized'], unique=True)
    op.create_table('report_templates',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('web', 'api', 'mobile', 'web3', 'network', 'physical', 'social_engineering', 'custom', name='template_category'), nullable=False),
    sa.Column('title_template', sa.Text(), nullable=True),
    sa.Column('description_template', sa.Text(), nullable=True),
    sa.Column('steps_template', sa.Text(), nullable=True),
    sa.Column('poc_template', sa.Text(), nullable=True),
    sa.Column('remediation_template', sa.Text(), nullable=True),
    sa.Column('cwe_id', sa.Integer(), nullable=True),
    sa.Column('cwe_name', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='severity_enum'), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('int', 'bool', 'str', 'json', name='config_value_type'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_ua', sa.Text(), nullable=True),
    sa.Column('current_session_id', app.models.GUID(), nullable=True),
    sa.Column('login_url_token_hash', sa.String(length=64), nullable=True),
    sa.Column('login_otp_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_used', sa.Boolean(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_url_token_hash')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reports',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('display_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('cvss_vector', sa.String(length=500), nullable=True),
    sa.Column('cwe_id', sa.Integer(), nullable=True),
    sa.Column('cwe_name', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', 'informational', name='report_severity_enum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'triaged', 'duplicate', 'informative', 'resolved', 'wont_fix', name='report_status_enum'), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('technical_details', sa.Text(), nullable=True),
    sa.Column('impact_statement', sa.Text(), nullable=True),
    sa.Column('proof_of_concept', sa.Text(), nullable=True),
    sa.Column('target_asset', sa.String(length=500), nullable=True),
    sa.Column('program_name', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('template_id', app.models.GUID(), nullable=True),
    sa.Column('bounty_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('bounty_currency', sa.String(length=10), nullable=True),
    sa.Column('bounty_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['report_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_display_id'), 'reports', ['display_id'], unique=True)
    op.create_table('ai_generation_jobs',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=True),
    sa.Column('provider', sa.Enum('anthropic', 'openai', 'gemini', 'ollama', name='ai_provider_enum'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_type', sa.Enum('full_report', 'section', 'improve', 'explain_cvss', 'suggest_remediation', 'suggest_cwe', name='ai_prompt_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='ai_job_status'), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_links',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('token', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('report_attachments',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=False),
    sa.Column('filename_original', sa.String(length=500), nullable=False),
    sa.Column('filename_stored', sa.String(length=100), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_attachments_report_id'), 'report_attachments', ['report_id'], unique=False)
    op.create_table('security_team_invites',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('otp_hash', sa.String(length=64), nullable=True),
    sa.Column('token_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extended_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('lock_reason', sa.Text(), nullable=True),
    sa.Column('first_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('followup_30_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_60_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followup_90_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('all_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_expiry_notified_3d', sa.Boolean(), nullable=False),
    sa.Column('resolved_expiry_notified_1d', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_security_team_invites_email'), 'security_team_invites', ['email'], unique=False)
    op.create_index(op.f('ix_security_team_invites_report_id'), 'security_team_invites', ['report_id'], unique=False)
    op.create_table('bounty_payments',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=True),
    sa.Column('method', sa.Enum('paypal', 'crypto', 'bank_transfer', 'other', name='payment_method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('paypal_payout_batch_id', sa.String(length=200), nullable=True),
    sa.Column('paypal_item_id', sa.String(length=200), nullable=True),
    sa.Column('paypal_recipient_email', sa.String(length=254), nullable=True),
    sa.Column('paypal_transaction_id', sa.String(length=200), nullable=True),
    sa.Column('crypto_address', sa.String(length=200), nullable=True),
    sa.Column('crypto_network', sa.String(length=50), nullable=True),
    sa.Column('crypto_tx_hash', sa.String(length=200), nullable=True),
    sa.Column('crypto_confirmations', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paypal_transaction_id')
    )
    op.create_index(op.f('ix_bounty_payments_report_id'), 'bounty_payments', ['report_id'], unique=False)
    op.create_table('followup_schedules',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=False),
    sa.Column('scheduled_days', sa.Enum('30', '60', '90', name='followup_days'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'skipped', name='followup_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followup_schedules_invite_id'), 'followup_schedules', ['invite_id'], unique=False)
    op.create_table('invite_activities',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=False),
    sa.Column('action', sa.Enum('link_clicked', 'setup_complete', 'reply_posted', 'bounty_set', 'status_changed', 'session_refreshed', 'account_locked', 'account_unlocked', 'followup_30_sent', 'followup_60_sent', 'followup_90_sent', 'followup_skipped', 'field_edit_proposed', 'field_edit_accepted', 'field_edit_rejected', name='invite_activity_action'), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_activities_action'), 'invite_activities', ['action'], unique=False)
    op.create_index(op.f('ix_invite_activities_invite_id'), 'invite_activities', ['invite_id'], unique=False)
    op.create_index(op.f('ix_invite_activities_performed_at'), 'invite_activities', ['performed_at'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=True),
    sa.Column('invite_id', app.models.GUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'discord', 'telegram', name='notification_channel'), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'retrying', name='notification_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_field_edits',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=False),
    sa.Column('field_name', sa.Enum('title', 'severity', 'cvss_vector', 'cvss_score', 'cwe_id', 'cwe_name', name='field_edit_field'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('proposed_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='field_edit_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_field_edits_report_id'), 'report_field_edits', ['report_id'], unique=False)
    op.create_table('report_replies',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('report_id', app.models.GUID(), nullable=False),
    sa.Column('author_type', sa.Enum('owner', 'security_team', name='reply_author_type'), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_replies_report_id'), 'report_replies', ['report_id'], unique=False)
    op.create_table('security_team_members',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('last_login_ua', sa.Text(), nullable=True),
    sa.Column('current_session_id', app.models.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_url_token_hash', sa.String(length=64), nullable=True),
    sa.Column('login_otp_hash', sa.String(length=64), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_url_token_hash')
    )
    op.create_index(op.f('ix_security_team_members_email'), 'security_team_members', ['email'], unique=True)
    op.create_table('security_team_sessions',
    sa.Column('id', app.models.GUID(), nullable=False),
    sa.Column('invite_id', app.models.GUID(), nullable=False),
    sa.Column('member_id', app.models.GUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_ip', sa.String(length=45), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['invite_id'], ['security_team_invites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['security_team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_team_sessions')
    op.drop_index(op.f('ix_security_team_members_email'), table_name='security_team_members')
    op.drop_table('security_team_members')
    op.drop_index(op.f('ix_report_replies_report_id'), table_name='report_replies')
    op.drop_table('report_replies')
    op.drop_index(op.f('ix_report_field_edits_report_id'), table_name='report_field_edits')
    op.drop_table('report_field_edits')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_invite_activities_performed_at'), table_name='invite_activities')
    op.drop_index(op.f('ix_invite_activities_invite_id'), table_name='invite_activities')
    op.drop_index(op.f('ix_invite_activities_action'), table_name='invite_activities')
    op.drop_table('invite_activities')
    op.drop_index(op.f('ix_followup_schedules_invite_id'), table_name='followup_schedules')
    op.drop_table('followup_schedules')
    op.drop_index(op.f('ix_bounty_payments_report_id'), table_name='bounty_payments')
    op.drop_table('bounty_payments')
    op.drop_index(op.f('ix_security_team_invites_report_id'), table_name='security_team_invites')
    op.drop_index(op.f('ix_security_team_invites_email'), table_name='security_team_invites')
    op.drop_table('security_team_invites')
    op.drop_index(op.f('ix_report_attachments_report_id'), table_name='report_attachments')
    op.drop_table('report_attachments')
    op.drop_table('external_links')
    op.drop_table('ai_generation_jobs')
    op.drop_index(op.f('ix_reports_display_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_table('report_templates')
    op.drop_index(op.f('ix_program_names_name_normalized'), table_name='program_names')
    op.drop_table('program_names')
    op.drop_table('csp_violations')
    op.drop_index(op.f('ix_access_logs_event_type'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_created_at'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
